### ISSUE TITLE
cannot add package

### ISSUE THREAD

**Issue by elmor34** [MeteorToys/MongolKit#1]
added  as meteor add msavin:mongol
also cloned to packages directory

the I get these messages :+1: 
regards

*W20150803-21:33:38.167(3)? (STDERR) 
W20150803-21:33:38.168(3)? (STDERR) /Users/gokhanaykan/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150803-21:33:38.168(3)? (STDERR) 						throw(ex);
W20150803-21:33:38.168(3)? (STDERR) 						      ^
W20150803-21:33:38.232(3)? (STDERR) Error: Tabular.Table options must specify collection
W20150803-21:33:38.232(3)? (STDERR)     at new Tabular.Table (packages/aldeed:tabular/common.js:20:1)
W20150803-21:33:38.232(3)? (STDERR)     at packages/yogiben:admin/lib/both/startup.coffee:100:27
W20150803-21:33:38.232(3)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150803-21:33:38.232(3)? (STDERR)     at adminCreateTables (packages/yogiben:admin/lib/both/startup.coffee:77:4)
W20150803-21:33:38.233(3)? (STDERR)     at __coffeescriptShare (packages/yogiben:admin/lib/both/startup.coffee:125:2)
W20150803-21:33:38.234(3)? (STDERR)     at /Volumes/work/mean3042/apache2/htdocs/e24m/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.*

**Comment by elmor34** [comment]
Solved. Thanks.
Problem comes from yogiben:admin
removed and solved.
